runtime: java11

handlers:

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /(.+\.html)
  static_files: \1
  upload: (.+\.html)

- url: /
  static_files: index.html
  upload: index\.html

- url: /.*
  secure: always
  script: auto